### ISSUE TITLE
Sikkerhet og Personvern

### ISSUE THREAD

**Issue by espenhalsen** [Altinn/altinn-support-dashboard#20]
### Description

Sikkerhet og Personvern

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/38
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/39
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/40
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/41
```
