### ISSUE TITLE
Testing og Kvalitetssikring

### ISSUE THREAD

**Issue by espenhalsen** [Altinn/altinn-support-dashboard#22]
### Description

Testing og Kvalitetssikring

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/46
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/47
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/48
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/49
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/71
```
