### ISSUE TITLE
Dokumentasjon og Support

### ISSUE THREAD

**Issue by espenhalsen** [Altinn/altinn-support-dashboard#23]
### Description

Dokumentasjon og Support

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/50
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/51
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/52
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/53
```
