### ISSUE TITLE
Kartlegge og planlegge av autentisering og autorisasjon (ID-porten integrasjon og/eller Azure AD)

### ISSUE THREAD

**Issue by espenhalsen** [Altinn/altinn-support-dashboard#38]
```[tasklist]
### Tasks
- [ ] Finne ut om man kan bruke "Authentication" på app service-nivå i Azure
- [ ] Finne ut hvordan man kan få lagd en AD-gruppe som inneholder de digdir.no-brukerne i kundeteam/ABS som skal ha tilgang
- [ ] Finne ut hvordan man kan autorisere i applikasjonskoden at innlogget bruker tilhører rett gruppe
```

**Comment by espenhalsen** [comment]
Bruke MSAL i prosjekt for integrering av Entra ID (Azure AD)
