### ISSUE TITLE
Sette opp infrastruktur i Azure

### ISSUE THREAD

**Issue by elsand** [Altinn/altinn-support-dashboard#70]
```[tasklist]
### Tasks
- [ ] Beskrive hva som trengs av Azure-ressurser (key vault, app service, application insights)
- [ ] Få avtalt et arbeidsmøte med Team Platform (ta kontakt med Espen Herskedal)
- [ ] Få opprettet subscriptions / ressursgrupper for hhv test-miljø og prod-miljø
```
