### ISSUE TITLE
Implentere innstillings-meny

### ISSUE THREAD

**Issue by loguecow** [Altinn/altinn-support-dashboard#83]
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/84
- [ ] https://github.com/Altinn/altinn-support-dashboard/issues/85
- [ ] Implementere valgfunksjon for språk
- [ ] Implementere knapp for utlogging
- [ ] Implementere knapp for relasting av side
- [ ] Vise status på om API er tilkoblet korrekt / fungerende
- [ ] Implementere darkmode knapp
```
