### ISSUE TITLE
Endringer i visning og små logikk

### ISSUE THREAD

**Issue by loguecow** [Altinn/altinn-support-dashboard#86]
```[tasklist]
### Tasks
- [x] tabell visning fjern info i vis rolle tabell (rolleid, beskrivelse -- )
- [x] Mer synlig visning til underenhet
- [x] mer synlig visning fokusert valg til organisasjon
- [x] KOMM underenhet visning fiks
- [x] Onclear prop til searchbar
- [x] Søk i kontakter fiks
```
